<?php

return [
    'backup_code' => env('BACKUP_CODE'),
    'backup_url' => env('BACKUP_URL'),
    'backup_zip_password' => env('BACKUP_ZIP_PASSWORD', 'secret123'),

    /*
    |--------------------------------------------------------------------------
    | Backup Paths
    |--------------------------------------------------------------------------
    |
    | The directories used when creating backups. These paths are relative to
    | the storage/app directory. The "backup" path is where generated backup
    | files will be written while the "storage" path defines the directory
    | that will be archived when creating a storage backup.
    |
    */
    'paths' => [
        'backup' => env('NOTIFIER_BACKUP_PATH', 'backups'),
        'storage' => env('NOTIFIER_STORAGE_PATH', 'public'),
    ],

    /*
    |--------------------------------------------------------------------------
    | Logging Channel
    |--------------------------------------------------------------------------
    |
    | All logs generated by the notifier package will be written using this
    | log channel.
    |
    */
    'log_channel' => env('NOTIFIER_LOG_CHANNEL', 'backup'),

    /*
    |--------------------------------------------------------------------------
    | Default Filesystem Disk
    |--------------------------------------------------------------------------
    |
    | The filesystem disk to be used for backup related file operations. This
    | should reference a local disk configuration so that the package can read
    | and write files on the filesystem.
    |
    */
    'default_disk' => env('NOTIFIER_DEFAULT_DISK', 'local'),
];
